package com.sloth.pontus.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sloth.pontus.entity.ResourceEntity;

import com.sloth.pontus.dao.ResourceEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig resourceEntityDaoConfig;

    private final ResourceEntityDao resourceEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        resourceEntityDaoConfig = daoConfigMap.get(ResourceEntityDao.class).clone();
        resourceEntityDaoConfig.initIdentityScope(type);

        resourceEntityDao = new ResourceEntityDao(resourceEntityDaoConfig, this);

        registerDao(ResourceEntity.class, resourceEntityDao);
    }
    
    public void clear() {
        resourceEntityDaoConfig.clearIdentityScope();
    }

    public ResourceEntityDao getResourceEntityDao() {
        return resourceEntityDao;
    }

}
